USE [master]
GO

/****** Object:  Database [HDeskDBellDB]    Script Date: 2020-02-24 3:44:41 AM ******/
CREATE DATABASE [HDeskDBellDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HDeskDBellDB.mdf', FILENAME = N'C:\Users\rochd\source\repos\HDeskBellWebApp\HDBellWebUI\App_Data\HDeskDBellDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HDeskDBellDB_log.ldf', FILENAME = N'C:\Users\rochd\source\repos\HDeskBellWebApp\HDBellWebUI\App_Data\HDeskDBellDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HDeskDBellDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HDeskDBellDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [HDeskDBellDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HDeskDBellDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HDeskDBellDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HDeskDBellDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HDeskDBellDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [HDeskDBellDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HDeskDBellDB] SET  MULTI_USER 
GO

ALTER DATABASE [HDeskDBellDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HDeskDBellDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HDeskDBellDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HDeskDBellDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HDeskDBellDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HDeskDBellDB] SET QUERY_STORE = OFF
GO

USE [HDeskDBellDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [HDeskDBellDB] SET  READ_WRITE 
GO


